export const addRoomField = {
    name: '',
    description: '',
    guests: 0,
    bedRoom: 0,
    bath: 0,
    price: 0,
    elevator: false,
    hotTub: false,
    pool: false,
    indoorFireplace: false,
    dryer: false,
    gym: false,
    kitchen: false,
    wifi: false,
    heating: false,
    cableTV: false,
    locationId:'',
  };
  